# Generated by Django 4.0.4 on 2022-05-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workday_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название услуги')),
                ('cost_price', models.PositiveIntegerField(verbose_name='Себестоимость')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(verbose_name='Стоимость')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('done', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
